name: face_scaner
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.1
  freezed_annotation: ^0.14.2
  get_it: ^7.1.3
  injectable: ^1.4.1
  provider: ^5.0.0

dev_dependencies:
  bloc_test: ^8.0.2
  build_runner: ^2.0.4
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
  injectable_generator: ^1.4.1
  lint: ^1.5.3
  mockito: ^5.0.10


flutter:
  uses-material-design: true
  assets:
    - assets/
